#!/usr/bin/env ruby
require 'rubygems'
require 'json'
require 'pusher'
require 'yaml'

# data = JSON.parse STDIN.read

# puts "#{JSON.generate data}"

tube_config = YAML.load_file('config.yml')
append_text = tube_config["description"]
json_input = JSON.parse STDIN.read

Pusher.app_id = '30507'
Pusher.key = 'afefd11a8f69dd2a425d'
Pusher.secret = '6f034e7a52ece851ea77'

json_input["payload"] << "\n#{append_text}"
json_input["sender"] = tube_config["name"]

Pusher['messages'].trigger('output', json_input) 
