#!/usr/bin/env python

import sys
import json

def main():
    msg = sys.stdin.readline()
    jsonObj = json.loads(msg)
    
    newPayload = hexEncode(jsonObj['payload'])
    jsonObj['payload'] = newPayload.encode('unicode_escape')
    sys.stdout.write(json.dumps(jsonObj) + "/n")

def hexEncode(msg):
    print msg.encode('hex')
    
    return bz2Encode(msg)+'Hex encoded.'
    
def bz2Encode(msg):
    print msg.encode('bz2_codec')
    
    return uuEncode(msg)+'BZ2 encoded.'

def uuEncode(msg):
    print msg.encode('uu_codec')
    
    return gzipEncode(msg)+'UU encoded.'
    
def gzipEncode(msg):
    print msg.encode('zlib_codec')
    
    return punyEncode(msg)+'Zip encoded.'

def punyEncode(msg):
    print msg.encode('punycode')
    
    return msg+'Punycoded.'


if __name__ == '__main__':
    main()