name: qrcode
display_name: QR code printer / scanner
description: >
    Encodes the message into a QR code, prints it out over Bluetooth, then scans it back in through an iPhone
invocation_method: pusher 
result_method: pusher
status: unstable