name:               globin
display_name:       ROT 13 Encoder
status:             stable
invocation_method:  stdin
result_method:      stdout
description: >
    Basic Python tube that ROT13 encodes the input payload
