#!/usr/bin/env python

import sys
import json

def main():
    msg = sys.stdin.readline()
    jsonObj = json.loads(msg)
    jsonObj['payload'] = jsonObj['payload'].encode('rot13')
    sys.stdout.write(json.dumps(jsonObj)+"\n")

if __name__ == '__main__':
    main()