#!/usr/bin/perl

use JSON;

$in = <>;
#print $in;

$json = new JSON;
$json_text = $json->allow_nonref->utf8->relaxed->decode($in);
$payload = $json_text->{payload};
$addition = '\nEncoded: UTF8, Language: Perl, Transport: Stdin / Stdout.")';
$new_payload = $payload . $addition;

my $data;
$data->{id}  = $json_text->{id};
$data->{payload} = $new_payload;

print $json->encode($data);