# rabbitmq: rabbitmq-server
# memcached: memcached -v
web: ./manage.py runserver
watch: watch.rb . localhost
# smtpd: python -m smtpd -n -c DebuggingServer localhost:1025
# celeryd: ./manage.py celeryd -E -l info
