#!/usr/local/bin/lua 

sf=string.format
json = require("json")
require("base64")

inStr = io.read()
jsonObj = json.decode(inStr)

jsonObj.payload = to_base64(jsonObj.payload)

jsonObj.payload = from_base64(jsonObj.payload)

jsonObj.payload = jsonObj.payload .. " \nEncoded: Base64, Language: Lua, Transport: Stdin / Stdout.")"

jsonStr = json.encode(jsonObj)
print(jsonStr)