#!/usr/bin/env python
from pyLaunchpad import launchpad
import logging

from basetube import BaseTube

logging.basicConfig(level=logging.DEBUG, format="%(asctime)s %(name)s %(levelname)s %(message)s")

log = logging.getLogger(__name__)


class LaunchpadTube(BaseTube):
    def handle(self, message):
        payload = message['payload']
        log.debug("payload")


def main():
    LaunchpadTube("launchpad").run()

if __name__ == '__main__':
    main()