#!/usr/bin/env python
import sys
import json
from pusher import Pusher

def main():
    p = Pusher(**{
        "app_id": '30507',
        "key": 'afefd11a8f69dd2a425d',
        "secret": '6f034e7a52ece851ea77'
    })
    message = json.loads(sys.stdin.read())
    
    message['encoding_scheme'] = "base64"
    message['encoded_payload'] = message['payload'].encode("base64")
    message['sender'] = "python_test"
    p['messages'].trigger("processing", message)
    
    
    
    
    del(message['sender'])
    del(message['encoding_scheme'])
    del(message['encoded_payload'])
    sys.stdout.write(json.dumps(message))

if __name__ == '__main__':
    main()